### PR TITLE
Get covers for books with no ASIN

### PR DESCRIPTION
**Pull request by Serized**
Search for ASIN numbers by title and author on amazon.
Most of the code comes from the calibre Amazon metadata plugin.

### CODE REVIEW

**Comment by lbschenkel** [comment]
Could you please amend this so the diff contains only the code you added?

**Comment by Serized** [comment]
I'm not sure what you mean. I changed the history so that there is only one diff file?

**Comment by lbschenkel** [comment]
No, it's because you changed whitespace for the existing code so if I merge as it is it'll appear that you modified all the lines instead of just the new code that you actually introduced.

If you don't know how to amend history it is OK, then I'll manually incorporate your changes instead of doing it via this PR.

**Comment by Serized** [comment]
Ah ok, I didn't remember changing this... It should work now

**Comment by lbschenkel** [comment]
Hi, I merged your code but I took the liberty of editing the commit slightly — I removed the change to the title/description in order to have a commit that only adds the scraping, plus tweaked the commit message. Since I changed your commit, it does not show as merged here.

When I have time I'll work on the Goodreads integration and most probably I'll end up refactoring your code as well.

**Pull request closed without merging**
